# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-28 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20180728_0813'),
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.Category'),
            preserve_default=False,
        ),
    ]
