# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-28 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merch',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Merch'},
        ),
        migrations.AlterField(
            model_name='merch',
            name='slug',
            field=models.SlugField(editable=False, max_length=300),
        ),
    ]
