# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-28 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
