# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-28 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20180728_0813'),
        ('merch', '0002_merch_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merch_typr', to='categories.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='merch',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merch', to='merch.MerchType'),
        ),
    ]
