# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-28 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_merch_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merch', to='categories.Category'),
        ),
    ]
