# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('merch', '0003_auto_20180728_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchtype',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merch',
            name='slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]
