# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('merch', '0004_auto_20180728_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchtype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
