# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-28 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('merch', '0005_merchtype_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merch',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Merch'},
        ),
    ]
